#!/bin/bash
# One-shot pre-market launcher.
#
# Run this BEFORE going to bed. It rewrites the LaunchAgent plist so
# the trader fires at 04:30 Costa Rica time (system local). Pre-market
# opens at 02:00 CR; 04:30 gives the operator coverage of the second
# half of pre-market plus the regular session opening at 07:30 CR.
#
# After this script exits, close the lid (with charger plugged in) or
# leave the laptop alone — at 04:30 launchd will run start_trader.sh,
# which brings up the docker IB Gateway, waits for port 4002, and then
# `caffeinate -ims trade_receiver --persist --IB`.
#
# Restore the production weekly schedule (02:00 CR Mon-Fri) any time:
#   cp scripts/com.tan.trader.plist ~/Library/LaunchAgents/
#   launchctl unload ~/Library/LaunchAgents/com.tan.trader.plist
#   launchctl load   ~/Library/LaunchAgents/com.tan.trader.plist
set -euo pipefail

PLIST=~/Library/LaunchAgents/com.tan.trader.plist
SCRIPT=/Users/tan/experiments/polygon.io/scripts/start_trader.sh
LOG_DIR=/Users/tan/experiments/polygon.io/logs/trader
FIRE_HH=04
FIRE_MM=30
NOW=$(date '+%H:%M:%S')

mkdir -p "$LOG_DIR"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Pre-market plist generated by arm_trader_430am.sh at ${NOW} -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tan.trader</string>
    <key>ProgramArguments</key>
    <array>
        <string>${SCRIPT}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>${FIRE_HH}</integer>
        <key>Minute</key><integer>${FIRE_MM}</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/launchd.out</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/launchd.err</string>
</dict>
</plist>
PLIST_EOF

launchctl unload "$PLIST" 2>/dev/null || true
launchctl load   "$PLIST"

echo "════════════════════════════════════════════════"
echo "  Pre-market launch armed"
echo "════════════════════════════════════════════════"
echo "  Now:   ${NOW}"
echo "  Fires: ${FIRE_HH}:${FIRE_MM}  (Costa Rica time)"
echo "  Plist: $PLIST"
echo "  Log:   $LOG_DIR/run_<timestamp>.log  (created when it fires)"
echo ""
echo "  In the morning, inspect the run with:"
echo "    ls -lt $LOG_DIR/"
echo "    tail -f $LOG_DIR/run_*.log"
echo ""
echo "  Cancel before it fires:"
echo "    launchctl unload $PLIST"
echo "════════════════════════════════════════════════"
