#!/bin/bash
# One-shot test launcher for the unattended trading flow.
#
# Run this in a terminal NOW; it rewrites the LaunchAgent plist so the
# trader fires exactly 5 minutes from the moment you invoked it. After
# this script exits you can close the lid (with charger plugged in),
# turn off the display, or just leave the laptop alone — at the
# scheduled minute, launchd will wake the user agent and run
# start_trader.sh, which brings up the docker IB Gateway, waits for
# port 4002, and then `caffeinate -ims trade_receiver --persist --IB`.
#
# Restore the production schedule (02:00 CR Mon-Fri) any time with:
#   cp scripts/com.tan.trader.plist ~/Library/LaunchAgents/
#   launchctl unload ~/Library/LaunchAgents/com.tan.trader.plist
#   launchctl load   ~/Library/LaunchAgents/com.tan.trader.plist
set -euo pipefail

PLIST=~/Library/LaunchAgents/com.tan.trader.plist
SCRIPT=/Users/tan/experiments/polygon.io/scripts/start_trader.sh
LOG_DIR=/Users/tan/experiments/polygon.io/logs/trader

# Fire 5 minutes from now. Use date -v to add minutes (BSD date).
FIRE_HH=$(date -v+5M +%H)
FIRE_MM=$(date -v+5M +%M)
NOW=$(date '+%H:%M:%S')

mkdir -p "$LOG_DIR"

cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- TEST plist generated by test_trader_in_5min.sh at ${NOW} -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.tan.trader</string>
    <key>ProgramArguments</key>
    <array>
        <string>${SCRIPT}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>${FIRE_HH}</integer>
        <key>Minute</key><integer>${FIRE_MM}</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/launchd.out</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/launchd.err</string>
</dict>
</plist>
PLIST_EOF

# Reload — unload is allowed to fail (first install)
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load   "$PLIST"

echo "════════════════════════════════════════════════"
echo "  Test scheduled"
echo "════════════════════════════════════════════════"
echo "  Now:   ${NOW}"
echo "  Fires: ${FIRE_HH}:${FIRE_MM}  (~5 min)"
echo "  Plist: $PLIST"
echo "  Log:   $LOG_DIR/run_<timestamp>.log  (created when it fires)"
echo ""
echo "  Watch live (in another terminal):"
echo "    tail -f $LOG_DIR/run_*.log $LOG_DIR/launchd.out $LOG_DIR/launchd.err 2>/dev/null"
echo ""
echo "  Cancel before it fires:"
echo "    launchctl unload $PLIST"
echo "════════════════════════════════════════════════"
